"""empty message

Revision ID: 59c79a8b963a
Revises: 4aaf62ca03c2
Create Date: 2021-06-03 00:21:02.735701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from uuid import uuid4

# revision identifiers, used by Alembic.
revision = '59c79a8b963a'
down_revision = '4aaf62ca03c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # dropping primary leys, using CASCADE to also delete foreign key constraints

    op.execute('ALTER TABLE communities.community DROP CONSTRAINT community_pkey CASCADE')
    op.execute('ALTER TABLE communities.community DROP COLUMN id')

    op.execute('ALTER TABLE communities.post DROP CONSTRAINT post_pkey CASCADE')
    op.execute('ALTER TABLE communities.post DROP COLUMN id')

    op.execute('ALTER TABLE communities.comment DROP CONSTRAINT comment_pkey CASCADE')
    op.execute('ALTER TABLE communities.comment DROP COLUMN id')


    # adding id columns with uuid type
    op.add_column(column = sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid4), schema='communities', table_name='community')  
    op.add_column(column = sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid4), schema='communities', table_name='post')
    op.add_column(column = sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid4), schema='communities', table_name='comment')
    
    # adding id column with uuid type for relations
    op.add_column(column = sa.Column('community_id', postgresql.UUID(as_uuid=True), nullable=False), schema='communities', table_name='post') 
    op.add_column(column = sa.Column('post_id', postgresql.UUID(as_uuid=True), nullable=False), schema='communities', table_name='comment') 

    # creating primary key constraints
    op.create_primary_key('community_pkey', 'community',  ['id'], schema='communities')
    op.create_primary_key('post_pkey', 'post',  ['id'], schema='communities')
    op.create_primary_key('comment_pkey', 'comment',  ['id'], schema='communities')
    
    # creating foreign key constraints
    op.create_foreign_key('fk_community_id_fkey', 'post', 'community', ['community_id'], ['id'], source_schema='communities', referent_schema='communities')
    op.create_foreign_key('fk_comment_post_id_fkey', 'comment', 'post', ['post_id'], ['id'], source_schema='communities', referent_schema='communities')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    op.drop_table('comment', schema='communities')
    op.drop_table('post', schema='communities')
    op.drop_table('community', schema='communities')
    op.drop_table('user', schema='users_info')
    """
    # ### end Alembic commands ###
